#include "transport_icon.h"

// 1 bpp masks, one 16-bit row each, MSB = leftmost pixel, in ti_glyph_t order
// (TI_USB, TI_BT, TI_WIFI). Edit the ASCII art beside the numbers, not the
// numbers: they were rasterised from it and the two are meant to be read
// together. Positional rather than [index]-designated — C++ has no array
// designators, and GCC rejects them outright.
static const uint16_t s_glyphs[TI_GLYPH_COUNT][TI_H] = {
  // TI_USB: arrow, stem, a round terminal on the left branch and a square one
  // on the right, ring at the foot.
  {
    0x0100,   // .......#........
    0x0180,   // .......##.......
    0x03c0,   // ......####......
    0x07ec,   // .....######.##..
    0x018c,   // .......##...##..
    0x21b0,   // ..#....##.##....
    0x11c0,   // ...#...###......
    0x0d80,   // ....##.##.......
    0x0380,   // ......###.......
    0x0180,   // .......##.......
    0x0180,   // .......##.......
    0x03c0,   // ......####......
    0x0660,   // .....##..##.....
    0x0420,   // .....#....#.....
    0x0660,   // .....##..##.....
    0x03c0,   // ......####......
  },
  // TI_BT: the Bluetooth rune — a stave with two chevrons off its right,
  // meeting at the stave's midpoint. Solid rather than hollow: at this size an
  // outlined triangle rasterises into two near-parallel lines and reads as a
  // slash.
  {
    0x1800,   // ...##...........
    0x1c00,   // ...###..........
    0x1f00,   // ...#####........
    0x1fc0,   // ...#######......
    0x1ff0,   // ...#########....
    0x1fc0,   // ...#######......
    0x1f00,   // ...#####........
    0x1c00,   // ...###..........
    0x1c00,   // ...###..........
    0x1f00,   // ...#####........
    0x1fc0,   // ...#######......
    0x1ff0,   // ...#########....
    0x1fc0,   // ...#######......
    0x1f00,   // ...#####........
    0x1c00,   // ...###..........
    0x1800,   // ...##...........
  },
  // TI_WIFI: two arcs over a dot. Two, not three — a faithful three-arc fan at
  // this size rasterises into flat bars that merge with the dot.
  {
    0x0000,   // ................
    0x0000,   // ................
    0x0000,   // ................
    0x0000,   // ................
    0x0000,   // ................
    0x0000,   // ................
    0x0ff0,   // ....########....
    0x3c3c,   // ..####....####..
    0x700e,   // .###........###.
    0xc003,   // ##............##
    0x07e0,   // .....######.....
    0x0e70,   // ....###..###....
    0x1818,   // ...##......##...
    0x03c0,   // ......####......
    0x03c0,   // ......####......
    0x03c0,   // ......####......
  },
};

void transportIconDraw(Display& d, int16_t x, int16_t y, ti_glyph_t glyph,
                       uint16_t fg, uint16_t bg) {
  if (glyph >= TI_GLYPH_COUNT) return;

  // One caller — the housekeeping loop — so a file-scope buffer is enough, and
  // it keeps 512 bytes off app_main's 3584-byte stack.
  static uint16_t px[TI_W * TI_H];
  const uint16_t* mask = s_glyphs[glyph];

  for (int row = 0; row < TI_H; row++) {
    for (int col = 0; col < TI_W; col++) {
      px[row * TI_W + col] = (mask[row] >> (TI_W - 1 - col)) & 1 ? fg : bg;
    }
  }
  d.drawImage565(x, y, TI_W, TI_H, px);
}
