#!/usr/bin/env python3
"""Convert the Jaguar logo (SVG or bitmap) into an RGB565 C header.

The ESP32 has no PSRAM on this board, so the logo is stored as a flash-resident
(.rodata) RGB565 array and streamed to the panel in bands at draw time. Cropping
to the artwork's bounding box keeps the array small — the Jaguar logo is a wide
3.6:1 mark, so the cropped bitmap is ~22 KB rather than the 115 KB a full
240x240 frame would cost.

The source art has a transparent background; it is composited onto --bg because
the panel has no alpha channel. Default is white, matching the boot screen's
rounded card that the logo sits on.

Usage:
  logo2header.py INPUT [-o main/logo_data.h] [--width 200] [--bg ffffff]
                       [--name LOGO] [--render-px 2400]

  INPUT may be an .svg (rendered with rsvg-convert, then downsampled) or any
  format Pillow can read.

Requires: Pillow. rsvg-convert (librsvg) is required only for .svg input.
"""

import argparse
import os
import shutil
import subprocess
import sys
import tempfile

try:
    from PIL import Image
except ImportError:
    sys.exit("error: Pillow is required (pip install Pillow)")


def load_source(path, render_px):
    """Return an RGBA image for `path`, rendering SVG at high resolution.

    SVG is rasterised well above the final size so the downscale to ~200 px
    keeps the thin jaguar outline smooth. rsvg-convert is used rather than
    Pillow's own SVG support because Pillow cannot read SVG at all.
    """
    if path.lower().endswith(".svg"):
        rsvg = shutil.which("rsvg-convert")
        if not rsvg:
            sys.exit("error: rsvg-convert not found (needed for .svg input)")
        with tempfile.NamedTemporaryFile(suffix=".png", delete=False) as tmp:
            out = tmp.name
        try:
            subprocess.run([rsvg, "-w", str(render_px), path, "-o", out],
                           check=True)
            img = Image.open(out).convert("RGBA")
            return img.copy()
        finally:
            os.unlink(out)
    return Image.open(path).convert("RGBA")


def crop_to_artwork(img, alpha_threshold=8):
    """Trim the transparent margin so the stored bitmap holds only artwork.

    Without this the padding baked into the SVG viewBox would be stored as
    white pixels, wasting flash and shrinking the mark on screen.
    """
    alpha = img.split()[3].point(lambda a: 255 if a > alpha_threshold else 0)
    bbox = alpha.getbbox()
    if bbox is None:
        sys.exit("error: source image is fully transparent")
    return img.crop(bbox)


def fit(img, width):
    """Scale to `width`, preserving aspect ratio (rounded to whole pixels)."""
    w, h = img.size
    height = max(1, round(h * width / w))
    return img.resize((width, height), Image.LANCZOS)


def composite(img, bg_hex):
    """Flatten onto an opaque background, matching the panel's lack of alpha."""
    bg_hex = bg_hex.lstrip("#")
    bg = tuple(int(bg_hex[i:i + 2], 16) for i in (0, 2, 4))
    flat = Image.new("RGB", img.size, bg)
    flat.paste(img, (0, 0), img)
    return flat


def to_rgb565_le(img, invert01=False):
    """Pack to little-endian RGB565, matching esp_lcd's panel endianness.

    This is the same wire format the serial "img" command uses, so the panel
    displays these bytes correctly without a byte swap.
    """
    raw = img.tobytes()          # RGB, 3 bytes per pixel
    out = bytearray(len(raw) // 3 * 2)
    for i in range(0, len(raw), 3):
        v = ((raw[i] & 0xF8) << 8) | ((raw[i + 1] & 0xFC) << 3) | (raw[i + 2] >> 3)
        j = i // 3 * 2
        out[j] = v & 0xFF
        out[j + 1] = (v >> 8) & 0xFF
    return out


def emit_header(name, width, height, data, dest, meta):
    # One uint16_t literal per pixel. The two bytes are combined here rather
    # than emitted as "0x12,0x34" — that would read as two separate
    # initializers and overflow the array.
    rows = []
    for i in range(0, len(data), 2):
        rows.append("0x%04x" % (data[i] | (data[i + 1] << 8)))
    # 16 values per line keeps the file readable without being enormous.
    lines = [",".join(rows[i:i + 16]) for i in range(0, len(rows), 16)]

    with open(dest, "w") as f:
        f.write("// Generated by tools/logo2header.py -- do not edit by hand.\n")
        f.write("// Source: %s\n" % meta)
        f.write("#pragma once\n#include <stdint.h>\n\n")
        f.write("#define %s_W %d\n" % (name, width))
        f.write("#define %s_H %d\n" % (name, height))
        f.write("\n// RGB565, little-endian. Lives in flash (.rodata): %d bytes.\n"
                % len(data))
        f.write("static const uint16_t %s_BITMAP[%s_W * %s_H] = {\n"
                % (name, name, name))
        for line in lines:
            f.write("  " + line + ",\n")
        f.write("};\n")


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("input")
    ap.add_argument("-o", "--output", default="main/logo_data.h")
    ap.add_argument("--width", type=int, default=200,
                    help="stored bitmap width in pixels (default 200)")
    ap.add_argument("--bg", default="ffffff",
                    help="background to composite transparency onto (default white,")
    ap.add_argument("--name", default="LOGO", help="C symbol prefix")
    ap.add_argument("--render-px", type=int, default=2400,
                    help="SVG rasterisation width before downscaling")
    args = ap.parse_args()

    img = load_source(args.input, args.render_px)
    img = crop_to_artwork(img)
    src_w, src_h = img.size
    img = fit(img, args.width)
    img = composite(img, args.bg)

    data = to_rgb565_le(img)
    emit_header(args.name, img.width, img.height, data, args.output,
                "%s (%dx%d cropped -> %dx%d)"
                % (os.path.basename(args.input), src_w, src_h,
                   img.width, img.height))

    print("%s -> %s" % (args.input, args.output))
    print("  crop %dx%d -> %dx%d, %.1f:1, %d bytes"
          % (src_w, src_h, img.width, img.height,
             img.width / img.height, len(data)))


if __name__ == "__main__":
    main()
